version: '3'
volumes:
  node_modules:
services:
  front:
    build: ./front
    ports:
      - '3000:3000'
    volumes:
      - './front:/works'
      - node_modules:/works/node_modules
    tty: true
    stdin_open: true
    
  go:
    build: ./go-app
    ports:
      - '8000:8000'
    env_file:
      - ./variables.env
    volumes:
      - './go-app:/app/go-app'
    tty: true
    stdin_open: true

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
    env_file:
      - variables.env
    ports:
      - '3306:3306'
